name: Prod CI/CD Pipeline - EC2 Docker

on:
  push:
    branches: [main]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: SonarQube Code Quality Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=myproject
            -Dsonar.sources=.
            -Dsonar.host.url=http://43.204.237.157:9000/

      - name: Docker Build
        run: |
          docker build -t myapp:latest .



      - name: Push to DockerHub
        run: |
          docker tag myapp:latest abhi0236/myapp:latest
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push abhi0236/myapp:latest

  deploy:
    needs: build-test-scan
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and Deploy Container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull abhi0236/myapp:latest
            docker stop myapp || true
            docker rm myapp || true
            docker run -d --name myapp -p 80:80 abhi0236/myapp:latest
